services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - COUNTER_URL=http://counter:3001
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/booksdb
    depends_on:
      - counter
      - mongo
    volumes:
      - ./uploads:/app/uploads
    networks:
      - library-net

  counter:
    build: ./counter
    ports:
      - "3001:3001" # для отладки
    volumes:
      - ./counter/data:/data
    networks:
      - library-net

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - library-net

networks:
  library-net:

volumes:
  mongo-data:
